/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BillingFieldsConfig, OdinPayErrorPayload, OdinPaySubmitPayload } from "./components/exerp-odin-cc-form/exerp-odin-cc-form";
export { BillingFieldsConfig, OdinPayErrorPayload, OdinPaySubmitPayload } from "./components/exerp-odin-cc-form/exerp-odin-cc-form";
export namespace Components {
    interface ExerpOdinCcForm {
        /**
          * Optional configuration to enable and customize billing fields. This object determines which optional billing fields are rendered and allows overriding their default labels and placeholders.  - For optional fields (e.g., `name`, `addressLine1`):   - `true`: Enables the field with default label and placeholder.   - `FieldCustomization` object (e.g., `{ label?: 'Custom Label', placeholder?: 'Custom Hint' }`):     Enables the field and applies the specified customizations.   - If a field key is omitted, the field is not rendered.  - For fields that are always structurally part of the form but can be customized   (e.g., `postalCode` label/placeholder, `cardInformation` label):   - Provide a `FieldCustomization` object to override default texts.  Example: `{   name: true, // Enable 'Name on Card' with defaults   addressLine1: { label: 'Street Address Line 1' }, // Custom label for address   city: { placeholder: 'Enter your city here' }, // Custom placeholder for city   postalCode: { label: 'Zip/Postal' } // Custom label for postal code }`  Refer to the `BillingFieldsConfig` and `FieldCustomization` type definitions within this file for the exact structure and available field names.
         */
        "billingFieldsConfig"?: BillingFieldsConfig;
        /**
          * The country code ('US' or 'CA') for which the payment form should be configured. This is mandatory and passed to OdinPay.js.
         */
        "countryCode": 'US' | 'CA';
        /**
          * Indicates if the payment method token generated by OdinPay.js should be treated as single-use (`true`) or intended for saving (`false`). Passed down from the facade. Defaults to `true`.
         */
        "isSingleUse": boolean;
        /**
          * Controls the level of logging output to the browser console. Passed down from the facade. Defaults to 'WARN'.
          * @defaultValue 'WARN'
          * @since x.y.z - Add version when released
         */
        "logLevel": LogLevel;
        /**
          * The short-lived public token obtained from the ODIN backend, required to initialize the OdinPay.js library. Passed down from the facade.
         */
        "odinPublicToken"?: string;
        /**
          * Specifies the type of payment method the form should handle. 'CARD' will render the credit card form. 'ACH' will render the bank account (ACH) form.
          * @defaultValue 'CARD'
         */
        "paymentMethodType": 'CARD' | 'ACH';
    }
}
export interface ExerpOdinCcFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLExerpOdinCcFormElement;
}
declare global {
    interface HTMLExerpOdinCcFormElementEventMap {
        "odinSubmitInternal": OdinPaySubmitPayload;
        "odinErrorInternal": OdinPayErrorPayload;
    }
    interface HTMLExerpOdinCcFormElement extends Components.ExerpOdinCcForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLExerpOdinCcFormElementEventMap>(type: K, listener: (this: HTMLExerpOdinCcFormElement, ev: ExerpOdinCcFormCustomEvent<HTMLExerpOdinCcFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLExerpOdinCcFormElementEventMap>(type: K, listener: (this: HTMLExerpOdinCcFormElement, ev: ExerpOdinCcFormCustomEvent<HTMLExerpOdinCcFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLExerpOdinCcFormElement: {
        prototype: HTMLExerpOdinCcFormElement;
        new (): HTMLExerpOdinCcFormElement;
    };
    interface HTMLElementTagNameMap {
        "exerp-odin-cc-form": HTMLExerpOdinCcFormElement;
    }
}
declare namespace LocalJSX {
    interface ExerpOdinCcForm {
        /**
          * Optional configuration to enable and customize billing fields. This object determines which optional billing fields are rendered and allows overriding their default labels and placeholders.  - For optional fields (e.g., `name`, `addressLine1`):   - `true`: Enables the field with default label and placeholder.   - `FieldCustomization` object (e.g., `{ label?: 'Custom Label', placeholder?: 'Custom Hint' }`):     Enables the field and applies the specified customizations.   - If a field key is omitted, the field is not rendered.  - For fields that are always structurally part of the form but can be customized   (e.g., `postalCode` label/placeholder, `cardInformation` label):   - Provide a `FieldCustomization` object to override default texts.  Example: `{   name: true, // Enable 'Name on Card' with defaults   addressLine1: { label: 'Street Address Line 1' }, // Custom label for address   city: { placeholder: 'Enter your city here' }, // Custom placeholder for city   postalCode: { label: 'Zip/Postal' } // Custom label for postal code }`  Refer to the `BillingFieldsConfig` and `FieldCustomization` type definitions within this file for the exact structure and available field names.
         */
        "billingFieldsConfig"?: BillingFieldsConfig;
        /**
          * The country code ('US' or 'CA') for which the payment form should be configured. This is mandatory and passed to OdinPay.js.
         */
        "countryCode": 'US' | 'CA';
        /**
          * Indicates if the payment method token generated by OdinPay.js should be treated as single-use (`true`) or intended for saving (`false`). Passed down from the facade. Defaults to `true`.
         */
        "isSingleUse"?: boolean;
        /**
          * Controls the level of logging output to the browser console. Passed down from the facade. Defaults to 'WARN'.
          * @defaultValue 'WARN'
          * @since x.y.z - Add version when released
         */
        "logLevel"?: LogLevel;
        /**
          * The short-lived public token obtained from the ODIN backend, required to initialize the OdinPay.js library. Passed down from the facade.
         */
        "odinPublicToken"?: string;
        /**
          * Fired when OdinPay.js returns an error during submission or if an internal setup error occurs. Contains the error message.
         */
        "onOdinErrorInternal"?: (event: ExerpOdinCcFormCustomEvent<OdinPayErrorPayload>) => void;
        /**
          * Fired when OdinPay.js successfully returns a payment method token after the user submits the form. The event detail contains the `paymentMethodId` and, if applicable, the `billingInformation` collected from the form.
         */
        "onOdinSubmitInternal"?: (event: ExerpOdinCcFormCustomEvent<OdinPaySubmitPayload>) => void;
        /**
          * Specifies the type of payment method the form should handle. 'CARD' will render the credit card form. 'ACH' will render the bank account (ACH) form.
          * @defaultValue 'CARD'
         */
        "paymentMethodType"?: 'CARD' | 'ACH';
    }
    interface IntrinsicElements {
        "exerp-odin-cc-form": ExerpOdinCcForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "exerp-odin-cc-form": LocalJSX.ExerpOdinCcForm & JSXBase.HTMLAttributes<HTMLExerpOdinCcFormElement>;
        }
    }
}
